### ISSUE TITLE
Provide icons for h4, h5, h6

### ISSUE THREAD

**Issue by zadam** [ckeditor/ckeditor5-heading#112]
theme/icons contains SVG only for H1, H2 and H3. If I configure more than that I get blank icon since there isn't one for H4 and further ... And creating new one visually consistent with the existing ones does not seem straightforward.

**Comment by Reinmar** [comment]
Hi! Thanks for reporting this. It indeed makes sense that we create these icons to keep them consistent. 

And we didn't create H4-H6 icons yet because no one asked for that, to be honest. It doesn't seem like that common case. Plus, there's the dropdown and if someone has more than 3 heading options perhaps they are choosing the dropdown.

**Comment by zadam** [comment]
Oh, I see, I forgot that it's possible to have headings in dropdown which I guess makes more sense for full H1-H6 rather than 6 separate buttons.
