### ISSUE TITLE
List of allowed headings should be configurable

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-heading#33]
It should be configurable if one wants to have all headers (`h2`, `h3` and `h4`), or only part of them.

**Comment by fredck** [comment]
Actually, the configuration should set how deep headings nesting is allowed, defaulting to 3, up to 5 (or 6 if we also configure to start with `h1`).

This is not a requirement right now tough.

**Comment by pjasiun** [comment]
Actually, in my case, I only need `h3` and `h4`. I want to be able to disable `h2`.

**Comment by Reinmar** [comment]
We simply need to expose [this](https://github.com/ckeditor/ckeditor5-headings/blob/2003c9b1de31f5475624681f097819110f5a45ad/src/headingsengine.js#L12-L17) in the `config.heading.<something>`. 

Also, I don't like the name of that property (which then repeates in the headings command API) because it's derived from the CKE4's format feature. So it should not be "formats" but... "headings"? :P 

PS. I'm going to rename this feature today, so it's not called "headings" finally (it should be "heading").

**Comment by fredck** [comment]
> PS. I'm going to rename this feature today, so it's not called "headings" finally (it should be "heading").

Hum... I don't think this is to be changed: https://github.com/ckeditor/ckeditor5-headings/issues/8#issuecomment-223593035

**Comment by oleq** [comment]
> We simply need to expose this in the config.heading.<something>.

@Reinmar: How would this work with locales? Because strings like `'Paragraph'`, `'Heading 1'` must be translated. How could people access our localization tools in such config?

**Comment by Reinmar** [comment]
> Hum... I don't think this is to be changed: #8 (comment)

Hm... so I'm a bit confused, TBH, cause I thought for the whole time that you prefer singular. I'm even pretty sure that you convince me to rename this feature :D. I'll report a separate ticket for that or comment on #8.

**Comment by Reinmar** [comment]
> @Reinmar: How would this work with locales? Because strings like 'Paragraph', 'Heading 1', etc. must be translated. How could people access our localization tools in such config?

It's tricky, but we had an idea for that. Basically, we can provide localization only for the default options. The "localisator", while building the editor, will scan for `t()` usage and should find all default names like "Paragraph" and "Heading1" (so we must put somewhere explicit `t('Paragraph')` expressions in the code). It will put them as translatable tokens into the translation service.

Now, if someone defined `config.heading` while initialising the editor, they couldn't use `t()` there  (because there's no editor yet) so we must treat those names as translation ids, not the final strings. The `t()` function will look for translation and if it couldn't find one, it will use the passed string. Which means that if you configured editor like this:

```js
headings: [
  { name: 'Paragraph, ... }
  { name: 'Super heading', ... }
}
```

And used Polish locale, then you'll have the following options: "Akapit", "Super heading". So basically, it's your fault that only half of the texts were translated. You need to take care of passing the right strings.

But, if you're just using a subset of the default settings (which contains "Paragraph" and "Heading 1-3") like this:

```js
headings: [
  { name: 'Paragraph, ... }
  { name: 'Heading 1', ... }
}
```

Then it will work perfectly even in Polish locale, because all strings will be translated automatically (cause we treat the setting as a translation ids).

**Comment by Reinmar** [comment]
@fredck: https://github.com/ckeditor/ckeditor5-headings/issues/6 there's a ticket for that. And the comment is later than the one in #8. So we changed the opinion :D.

**Comment by fredck** [comment]
Well, I don't see much discussion there, still "heading" sounds weird.
