### ISSUE TITLE
Separate commands for each heading

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-heading#53]
It's more and more popular to have separate buttons for headers:

Slack post editor:
![screen shot 2016-12-21 at 17 29 53](https://cloud.githubusercontent.com/assets/1166967/21397244/54264024-c7a3-11e6-978a-479ea633efaf.png)

medium.com:
![screen shot 2016-12-21 at 17 31 00](https://cloud.githubusercontent.com/assets/1166967/21397510/5621a35e-c7a4-11e6-9840-41d8155d8191.png)

paper.dropbox.com:
![screen shot 2016-12-21 at 17 40 25](https://cloud.githubusercontent.com/assets/1166967/21397567/9dfd1c62-c7a4-11e6-8299-68864ed0ce23.png)

It made me think about another way of implementing headers. Consider this:

Each header (P, H1, H2) have it's own command, which can be active or not or can enabled or disabled.

Each header provides the dropdown item connected to that command. It could also provide, ready to use, buttons added to `componentFactory`.

Then, on top of it, the dropdown can combine these commands/items: it is enabled if any command is enabled and display the active option. Note that such dropdown menu could be used for any collection of commands in the future.

What we get is flexibility. The developer decides how the toolbar will look like: if he wants to have separated icons, he can. If he wants to group some options in the dropdown, he can as well.

Also, it will be possible to disable a single header level, what is needed for https://github.com/ckeditor/ckeditor5-heading/issues/39.

**Comment by Reinmar** [comment]
> What we get is flexibility. The developer decides how the toolbar will look like: if he wants to have separated icons, he can

That's possible now – just create your own buttons for this single command which we have now and bind them accordingly. Not a problem at all.

If we split the command into multiple ones, then the implementation of this feature will become more complicated, because it's now creating a single drop down, which label would need to be inherited from multiple commands' state. So the current implementation is just simpler.

If that was the entire picture, I'd say we shouldn't touch it. Either creating your separate buttons is a bit more complicated or creating a doprdown is a bit more complicated. The feature should not implement both at the same time and the only option would be to have two features.

However, we've been talking about simple buttons -> dropdown transformation. Even, based on a simple toolbar config. This means that we'll need utils which allow you to convert separate commands (or rather buttons, if that's to be a UI-oriented feature) into a dropdown anyway, hence, it makes more senses to split the heading command.

The problem is that we don't have the toolbar configuration designed yet, so it's a bit risky that we'd have to work on this twice. So before we start, I'd like to see some design (aka feasibility study) for that.

**Comment by pjasiun** [comment]
> That's possible now – just create your own buttons for this single command which we have now and bind them accordingly. Not a problem at all.

Setting buttons to be active or not is not a problem, but if we would like to disable a simple heading level it's not doable. Such feature might be useful to implement #39 or maybe even #33. But I agree that it's not essential for the heading feature (to be honest I'm not sure if we need something like #39). 

> The feature should not implement both at the same time and the only option would be to have two features.

I believe such feature should be provided as a part of this package because it's very common scenario and it's very simple code. I can image the editor which has both: big top toolbar with a dropdown and a small contextual toolbar with buttons.
