### ISSUE TITLE
Why the dropdown has a tooltip?

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-heading#71]
As started in https://github.com/ckeditor/ckeditor5-heading/pull/69#discussion_r108400243 and well visible on:

![image](https://cloud.githubusercontent.com/assets/156149/24404872/1eb96774-13c3-11e7-99be-6ae5d9728638.png)

The tooltip doesn't seem to be useful. The dropdown, unlike most buttons, has a label, so the tooltip duplicates it. IMO, it's totally superfluous.

@oleq pointed me to #55 for explanation why we have the tooltip, but it's only slightly related to "why". It's more focused on what to display there. So I'd like to ask the initial "why".

**Comment by Reinmar** [comment]
PS. After we answer "why", let's also answer what should be displayed in that tooltip (if we want to keep it). Currently, the label says one of "Paragraph", "Heading X", "Choose heading" and the tooltip is always "Heading"  which looks kinda funny. And I can't think of what could be displayed there so it doesn't look odd ;)

**Comment by oleq** [comment]
Some insights on the subject:

1. http://ux.stackexchange.com/a/1258
2. https://msdn.microsoft.com/en-us/library/windows/desktop/dn742443.aspx#is_this_the_right_control_
3. https://msdn.microsoft.com/en-us/library/windows/desktop/dn742443.aspx#design_concepts

> But if the text you use in a tooltip is a redundant rehash of the label, then it's pointless. The unfortunate thing about tooltips is that they cover up the area underneath them. So excessive tooltips can become annoying to the user, especially if the user is trying to ignore them anyway.

> Does a control have a text label? If not, use a tooltip to provide the label. Note that most controls should be labeled and therefore not have tooltips. Toolbar controls and command buttons with graphic labels should have tooltips.

> Helpful. Tip text must be informative. It shouldn't be obvious or just repeat what is already on the screen.

The conclusion is that we should get rid of the tooltip here because it's redundant. And I think I agree with it.

But... the only reason I see to leave it looks like this:
![image](https://cloud.githubusercontent.com/assets/1099479/24548306/cb55edce-1614-11e7-83db-a3c0ce8e48c4.png)

The dropdown button is optimized to display the English label, which length will vary across different languages. And since the width of the dropdown button **must** be fixed to avoid the situation where dropdown is resizing (and totally disrupting the shape and flow of the toolbar) as the selected item changes, in some languages the label will be trimmed. By how much? Hard to tell. Supposedly, such trimming could make the label so obscure, the user wouldn't understand it at first glance. And this is where the tooltip kicks in, providing the full label.

It's probably up to the developer to tune the CSS so the label is fully visible but still it seems a valid use case for the tooltip.

**Comment by fredck** [comment]
I think that there should be one and only way for the user to check the name of the toolbar features and this is the tooltip. When moving the mouse through buttons and dropdowns the behavior would then be consistent.

Other than that, there are other very clear case that benefit from the tooltip, like the "font size" dropdown where you just see the number representing the current size.

Btw, showing tooltips seems to be consistent with other applications as well.

The mistake we did was most probably have used the heading dropdown to "sometimes" show its label and other times the current value. IMHO, already presented somewhere else, just values should be there.

Then, ofc, the proper tooltip should be found for it. I would go radical with it and call it "Paragraph styles" and the paragraph option inside the dropdown would be "Normal text".
